### PR TITLE
Framework uplift

### PR DESCRIPTION
**Pull request by Adipa-G**
Converted the library to netstandard2 to make it compatible with dotnet core
Uplifted the net framework version to 4.7.2

### CODE REVIEW

**Comment by alonam** [comment]
@Adipa-G Awesome work! Thank you for giving this project some love. It's been a while.
You're also invited to join us at [AnyStatus/Plugins](https://github.com/AnyStatus/Plugins)

**Comment by alonam** [comment]
@Adipa-G Build failed...
https://ci.appveyor.com/project/AlonAmsalem/nload

**Comment by Adipa-G** [comment]
Hi,

Looks like we may need to use a later version of MSBuild in order to build
the solution.
I tried the build with MSBuild in my local machine (VS2019 community
edition). This ships with the MSBuild version 16.0.

[image: image.png]

Unfortunately since the project has WPF components it appears that we are
not able to use *dotnet build* command.
https://github.com/JetBrains/teamcity-dotnet-plugin/issues/105
https://github.com/dotnet/cli/issues/6732

Let me know what you think.

Many thanks,
Adipa

**Comment by alonam** [comment]
Tried to change VS version on AppVeyor,, no change
https://ci.appveyor.com/project/AlonAmsalem/nload-ucpcx

It's ok to disable WPF projects in Release mode for now

**Comment by Adipa-G** [comment]
Hi,

Looks like the build wasn't kicked off. The log file is empty.

Many Thanks,
Adipa

**Pull request merged**
